# Generated by Django 4.1.4 on 2022-12-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('president', models.CharField(max_length=150)),
                ('manager', models.CharField(max_length=150)),
                ('name_of_field', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport')),
            ],
        ),
    ]
