# Generated by Django 4.1.4 on 2022-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Sport'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team'},
        ),
        migrations.AddField(
            model_name='team',
            name='image_link',
            field=models.TextField(default='entry'),
            preserve_default=False,
        ),
    ]
