# Generated by Django 4.1.4 on 2022-12-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_sport_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image_link', models.TextField()),
                ('teams', models.ManyToManyField(to='sports.team')),
            ],
        ),
    ]
