# Generated by Django 4.1.4 on 2022-12-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='s'),
            preserve_default=False,
        ),
    ]
